version: "3"

services:
  db:
    image: postgres
    platform: linux/arm64
    environment:
      POSTGRES_DB: IMCM
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/db:/var/lib/postgresql/data
  backend:
    # platform: linux/amd64
    build: ./backend
    command: bash -c "python manage.py migrate && python manage.py loaddata data.json && python manage.py runserver 0.0.0.0:8000"
    # command: bash -c "python manage.py reset_db --noinput --close-sessions"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  celery:
    build: ./backend
    command: celery -A config worker -l info
    volumes:
      - ./backend:/backend
    depends_on:
      - db
      - redis
