name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Run Tests
      env:
        SECRET_KEY: ${{secret.SECRET_KEY}}
        RAPID_API: ${{secret.RAPID_API}}
        EMAIL_HOST_PASSWORD: ${{secret.EMAIL_PASSWD}}
        SCRAPFLY_KEY: ${{secret.SCRAPFLY_KEY}}
        ST_APP_KEY: ${{secret.ST_APP_KEY}}
        SALESFORCE_CONSUMER_KEY: ${{secret.SALESFORCE_CONSUMER_KEY}}
        SALESFORCE_CONSUMER_SECRET: ${{secret.SALESFORCE_CONSUMER_SECRET}}
        STRIPE_PUBLISHABLE_KEY: ${{secret.STRIPE_PUBLIC_KEY}}
        STRIPE_LIVE_SECRET_KEY: ${{secret.STRIPE_SECRET_KEY}}
        REDIS_URL: ${{secret.REDIS_URL}}
        EMAIL: ${{secret.EMAIL}}
      run: |
        cd backend
        pytest
