name: Django CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run Tests
        env:          
          DJANGO_SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
          EMAIL: ${{secrets.EMAIL}}
          EMAIL_PASSWD: ${{secrets.EMAIL_PASSWD}}
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          REDIS_URL: ${{secrets.REDIS_URL}}
          SALESFORCE_CONSUMER_KEY: ${{secrets.SALESFORCE_CONSUMER_KEY}}
          SALESFORCE_CONSUMER_SECRET: ${{secrets.SALESFORCE_CONSUMER_SECRET}}
          SCRAPFLY_KEY: ${{secrets.SCRAPFLY_KEY}}
          ST_APP_KEY: ${{secrets.ST_APP_KEY}}
          STRIPE_SECRET_KEY: ${{secrets.STRIPE_SECRET_KEY }}
          STRIPE_SECRET_KEY_TEST: ${{secrets.STRIPE_SECRET_KEY_TEST }}
          STRIPE_PUBLIC_KEY: ${{secrets.STRIPE_PUBLIC_KEY }}
          STRIPE_PUBLIC_KEY_TEST: ${{secrets.STRIPE_PUBLIC_KEY_TEST }}
          
        run: |
          cd backend
          python manage.py makemigrations
          pytest
